baseurl: ""
url: "http://atomix.io"

permalink: pretty
markdown: kramdown
highlighter:
kramdown:
  input: GFM
  enable_coderay: false
  syntax_highlighter_opts:
    disable : true

atomix-version: 1.0.0-rc9
copycat-version: 1.1.4
catalyst-version: 1.1.1
