baseurl: ""
url: "http://atomix.io"

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: none
  use_coderay: false

atomix-version: 0.1.0-beta4
copycat-version: 1.0.0-beta4
catalyst-version: 1.0.0-rc2

javadoc-version: 0.1.0