baseurl: "/copycat" # the subpath of your site, e.g. /blog/
url: "http://kuujo.github.io" # the base hostname & protocol for your site

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  use_coderay: true
  coderay:
    coderay_line_numbers: nil

version: 0.6.0-SNAPSHOT