baseurl: ""
url: "http://atomix.io"

permalink: pretty
markdown: kramdown
highlighter:
kramdown:
  input: GFM
  enable_coderay: false
  syntax_highlighter_opts:
    disable : true

atomix-version: 0.1.0-rc2
copycat-version: 1.0.0-rc2
catalyst-version: 1.0.2

javadoc-version: 0.1.0