baseurl: "/copycat"
url: "http://kuujo.github.io"

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: none
  use_coderay: false

version: 0.1.0-SNAPSHOT
javadoc-version: 0.1.0