baseurl: "/copycat"
url: "http://kuujo.github.io"

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  use_coderay: true
  coderay:
    coderay_line_numbers: nil

version: 1.0.0-SNAPSHOT
javadoc-version: 1.0.0