baseurl: ""
url: "http://atomix.io"

permalink: pretty
highlighter: null
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: none
  use_coderay: false

atomix-version: 0.1.0-beta5
copycat-version: 1.0.0-beta6
catalyst-version: 1.0.0-rc6

javadoc-version: 0.1.0